import { ICategoriesStoreTabData } from "@/types/categories-store-tab/categoriesStoreTab.type";

export const CATEGORIES_TAB_DATA: ICategoriesStoreTabData[] = [
  {
    id: "1",
    title: "Accessories",
    products: 1,
    created_date: "2025-02-14T00:28:00",
    created_by: "Jaimin Valand",
    updated_date: null,
    updated_by: null,
    status: "active",
    hasChildren: true,
    subRows: [
      {
        id: "21",
        title: "Bags",
        products: 1,
        created_date: "2025-02-14T00:28:00",
        created_by: "Jaimin Valand",
        updated_date: "",
        updated_by: "",
        status: "inactive",
        hasChildren: true,
        subRows: [
          {
            id: "23",
            title: "Backpacks",
            products: 1,
            created_date: "2025-02-14T00:28:00",
            created_by: "Jaimin Valand",
            updated_date: "",
            updated_by: "",
            status: "active",
            hasChildren: false,
          },
        ],
      },
    ],
  },
  {
    id: "2",
    title: "Men",
    products: 2,
    created_date: "2025-02-14T00:28:00",
    created_by: "Jaimin Valand",
    updated_date: null,
    updated_by: null,
    status: "active",
    hasChildren: true,
    subRows: [
      {
        id: "24",
        title: "Polos",
        products: 1,
        created_date: "2025-02-14T00:28:00",
        created_by: "Jaimin Valand",
        updated_date: "",
        updated_by: "",
        status: "inactive",
        hasChildren: true,
        subRows: [
          {
            id: "27",
            title: "Short Sleeve",
            products: 1,
            created_date: "2025-02-14T00:28:00",
            created_by: "Jaimin Valand",
            updated_date: "",
            updated_by: "",
            status: "active",
            hasChildren: false,
          },
        ],
      },
      {
        id: "29",
        title: "Hoodies & Sweatshirts",
        products: 1,
        created_date: "2025-02-14T00:28:00",
        created_by: "Jaimin Valand",
        updated_date: "",
        updated_by: "",
        status: "inactive",
        hasChildren: true,
        subRows: [
          {
            id: "27",
            title: "Hoodies",
            products: 1,
            created_date: "2025-02-14T00:28:00",
            created_by: "Jaimin Valand",
            updated_date: "",
            updated_by: "",
            status: "active",
            hasChildren: false,
          },
        ],
      },
    ],
  },
  {
    id: "3",
    title: "Women",
    products: 2,
    created_date: "2025-02-14T00:28:00",
    created_by: "Jaimin Valand",
    updated_date: null,
    updated_by: null,
    status: "inactive",
    hasChildren: true,
    subRows: [
      {
        id: "32",
        title: "Quarter Zips & Pullovers",
        products: 1,
        created_date: "2025-02-14T00:28:00",
        created_by: "Jaimin Valand",
        updated_date: "",
        updated_by: "",
        status: "inactive",
        hasChildren: true,
        subRows: [
          {
            id: "33",
            title: "1-4 Zips",
            products: 1,
            created_date: "2025-02-14T00:28:00",
            created_by: "Jaimin Valand",
            updated_date: "",
            updated_by: "",
            status: "active",
            hasChildren: false,
          },
        ],
      },
      {
        id: "45",
        title: "Hoodies & Sweatshirts",
        products: 1,
        created_date: "2025-02-14T00:28:00",
        created_by: "Jaimin Valand",
        updated_date: "",
        updated_by: "",
        status: "inactive",
        hasChildren: true,
        subRows: [
          {
            id: "34",
            title: "Hoodies",
            products: 1,
            created_date: "2025-02-14T00:28:00",
            created_by: "Jaimin Valand",
            updated_date: "",
            updated_by: "",
            status: "active",
            hasChildren: false,
          },
        ],
      },
    ],
  },
];
