export const generalTabDummyData = {
  businessName: "1",
  storeDisplayName: "Sample Store",
  businessCategory: "1",
  programId: "1245",
  email: "store@example.com",
  domainTypeId: "1",
  payByMethod: 1,
  salesPerson: "1",
  storeOwnerFirstName: "Jane",
  storeOwnerLastName: "Smith",
  password: "",
  storeName: "Sample Store Name",
  teamName: "1",
  accessUrl: "sample-store.com",
  bcCustomerId: "BC123",
  bcLocationCode: "LOC1",
  estShipDate: new Date("2024-03-20"),
  followUpDays: "30",
  isPasswordProtected: true,
  jobTitle: "Store Manager",
  department: "Sales",
  storeOwnerEmail: "owner@example.com",
  company: "Sample Company",
  streetAddress: "123 Main St",
  aptSuite: "Suite 100",
  zipCode: "12345",
  storeCity: "Vancouver",
  storeOwnerCountry: "CA",
  storeOwnerState: "BC",
  storePhone: "555-0123",
  storeLogo: "logo-url.jpg",
  emailLogo: "email-logo.jpg",
  openStoreDate: new Date("2024-01-01"),
  closeStoreData: new Date("2024-12-31"),
  customerAddress: [
    {
      id: 1,
      firstname: "Bill",
      lastName: "Jones",
      email: "bill@example.com",
      address1: "456 Billing St",
      address2: "Floor 2",
      suite: "200",
      city: "Vancouver",
      state: "BC",
      postalCode: "67890",
      fax: "555-0124",
      phone: "555-0125",
      countryName: "CA",
      countryCode: "CA",
      addressType: "B" as "B",
      isDefault: true,
      recStatus: "A",
      rowVersion: "1.0",
      OtherState: "",
    },
    {
      id: 2,
      firstname: "Ship",
      lastName: "Smith",
      email: "ship@example.com",
      address1: "789 Shipping St",
      address2: "Unit 3",
      suite: "300",
      city: "Vancouver",
      state: "BC",
      postalCode: "12345",
      fax: "555-0126",
      phone: "555-0127",
      countryName: "CA",
      countryCode: "CA",
      addressType: "S" as "S",
      isDefault: true,
      recStatus: "A",
      rowVersion: "1.0",
      OtherState: "",
    },
  ],
};

export const generalTabInitialValues = {
  businessName: "",
  storeDisplayName: "",
  businessCategory: "",
  programId: "1245",
  email: "",
  domainTypeId: "",
  payByMethod: 0,
  salesPerson: "",
  storeOwnerFirstName: "",
  storeOwnerLastName: "",
  password: "",
  storeName: "",
  teamName: "",
  accessUrl: "",
  bcCustomerId: "",
  bcLocationCode: "",
  estShipDate: new Date(),
  followUpDays: "",
  isPasswordProtected: false,
  jobTitle: "",
  department: "",
  storeOwnerEmail: "",
  company: "",
  streetAddress: "",
  aptSuite: "",
  zipCode: "",
  storeCity: "",
  storeOwnerCountry: "",
  storeOwnerState: "",
  storePhone: "",
  storeLogo: "",
  emailLogo: "",
  openStoreDate: new Date(),
  closeStoreData: new Date(),
  customerAddress: [
    {
      id: 0,
      firstname: "",
      lastName: "",
      email: "",
      address1: "",
      address2: "",
      suite: "",
      city: "",
      state: "",
      postalCode: "",
      fax: "",
      phone: "",
      countryName: "",
      countryCode: "",
      addressType: "B" as "B",
      isDefault: true,
      recStatus: "A",
      rowVersion: "",
      OtherState: "",
    },
    {
      id: 0,
      firstname: "",
      lastName: "",
      email: "",
      address1: "",
      address2: "",
      suite: "",
      city: "",
      state: "",
      postalCode: "",
      fax: "",
      phone: "",
      countryName: "",
      countryCode: "",
      addressType: "S" as "S",
      isDefault: true,
      recStatus: "",
      rowVersion: "",
      OtherState: "",
    },
  ],
};

export const COUNTRY_OPTIONS = [
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
];

export const STATE_OPTIONS = [
  { value: "AB", label: "Alberta" },
  { value: "BC", label: "British Columbia" },
  { value: "MB", label: "Manitoba" },
  { value: "NB", label: "New Brunswick" },
];
