import { IGetOrdersItem } from "@/services/order/getOrders.service";

export const ordersData: IGetOrdersItem[] = [
  {
    orderStatus: "Pending",
    bcStatus: "Awaiting Payment",
    order: "ORD001",
    storeName: "Fashion Store",
    date: "2024-01-15",
    customerBillingInfo: {
      firstName: "John",
      lastName: "Smith",
      city: "New York",
      state: "NY",
      pincode: "10001",
      streetAddress1: "123 Main St",
      streetAddress2: "Apt 4B",
    },
    total: 299.99,
    paymentType: "Credit Card",
    paymentStatus: "Pending",
    fulfillmentStatus: "Not Started",
    items: [
      {
        productName: "Summer T-Shirt",
        productPrice: 49.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/tshirt.jpg",
        productSku: "TS001",
        productColor: "Blue",
        productTotal: 99.98,
      },
      {
        productName: "Denim Jeans",
        productPrice: 89.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/jeans.jpg",
        productSku: "DJ001",
        productColor: "Dark Blue",
        productTotal: 89.99,
      },
    ],
    shippingMethod: "Standard Shipping",
    storeLogoUrl: "https://example.com/store1-logo.png",
    name: "Summer Collection Cart",
    createdDate: "2024-01-15T10:30:00",
    createdName: "John Smith",
    modifiedDate: "2024-01-15T14:45:00",
    modifiedName: "Jane Doe",
    email: "customer1@example.com",
    customerId: "CUST001",
    shoppingCartId: "CART001",
    subTotal: 299.99,
  },
  {
    orderStatus: "Processing",
    bcStatus: "Paid",
    order: "ORD002",
    storeName: "Electronics Hub",
    date: "2024-01-14",
    customerBillingInfo: {
      firstName: "Michael",
      lastName: "Johnson",
      city: "Los Angeles",
      state: "CA",
      pincode: "90001",
      streetAddress1: "456 Oak Ave",
      streetAddress2: "Unit 7",
    },
    total: 849.99,
    paymentType: "PayPal",
    paymentStatus: "Completed",
    fulfillmentStatus: "In Progress",
    items: [
      {
        productName: "4K Smart TV",
        productPrice: 599.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/tv.jpg",
        productSku: "TV001",
        productColor: "Black",
        productTotal: 599.99,
      },
      {
        productName: "Soundbar",
        productPrice: 249.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/soundbar.jpg",
        productSku: "SB001",
        productColor: "Black",
        productTotal: 249.99,
      },
    ],
    shippingMethod: "Express Shipping",
    storeLogoUrl: "https://example.com/store2-logo.png",
    name: "Tech Gadgets Cart",
    createdDate: "2024-01-14T09:15:00",
    createdName: "Mike Johnson",
    modifiedDate: "2024-01-14T16:20:00",
    modifiedName: "Sarah Wilson",
    email: "customer2@example.com",
    customerId: "CUST002",
    shoppingCartId: "CART002",
    subTotal: 849.99,
  },
  {
    orderStatus: "Completed",
    bcStatus: "Fulfilled",
    order: "ORD003",
    storeName: "Home Decor",
    date: "2024-01-13",
    customerBillingInfo: {
      firstName: "Emily",
      lastName: "Brown",
      city: "Chicago",
      state: "IL",
      pincode: "60601",
      streetAddress1: "789 Pine Rd",
      streetAddress2: "",
    },
    total: 459.99,
    paymentType: "Credit Card",
    paymentStatus: "Completed",
    fulfillmentStatus: "Shipped",
    items: [
      {
        productName: "Table Lamp",
        productPrice: 79.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/lamp.jpg",
        productSku: "TL001",
        productColor: "White",
        productTotal: 159.98,
      },
      {
        productName: "Throw Pillows",
        productPrice: 29.99,
        productStatus: "In Stock",
        productQuantity: 4,
        productImage: "https://example.com/pillows.jpg",
        productSku: "TP001",
        productColor: "Beige",
        productTotal: 119.96,
      },
      {
        productName: "Wall Art",
        productPrice: 89.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/art.jpg",
        productSku: "WA001",
        productColor: "Multicolor",
        productTotal: 179.98,
      },
    ],
    shippingMethod: "Ground Shipping",
    storeLogoUrl: "https://example.com/store3-logo.png",
    name: "Living Room Items",
    createdDate: "2024-01-13T11:45:00",
    createdName: "Emily Brown",
    modifiedDate: "2024-01-13T15:30:00",
    modifiedName: "Emily Brown",
    email: "customer3@example.com",
    customerId: "CUST003",
    shoppingCartId: "CART003",
    subTotal: 459.99,
  },
  {
    orderStatus: "Pending",
    bcStatus: "Awaiting Payment",
    order: "ORD004",
    storeName: "Sports Gear",
    date: "2024-01-15",
    customerBillingInfo: {
      firstName: "Alex",
      lastName: "Turner",
      city: "Houston",
      state: "TX",
      pincode: "77001",
      streetAddress1: "321 Elm St",
      streetAddress2: "Suite 12",
    },
    total: 199.99,
    paymentType: "Debit Card",
    paymentStatus: "Pending",
    fulfillmentStatus: "Not Started",
    items: [
      {
        productName: "Running Shoes",
        productPrice: 129.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/shoes.jpg",
        productSku: "RS001",
        productColor: "Black/Red",
        productTotal: 129.99,
      },
      {
        productName: "Sports Water Bottle",
        productPrice: 34.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/bottle.jpg",
        productSku: "WB001",
        productColor: "Blue",
        productTotal: 69.98,
      },
    ],
    shippingMethod: "Standard Shipping",
    storeLogoUrl: "https://example.com/store4-logo.png",
    name: "Fitness Equipment",
    createdDate: "2024-01-15T08:30:00",
    createdName: "Alex Turner",
    modifiedDate: "2024-01-15T09:45:00",
    modifiedName: "Alex Turner",
    email: "customer4@example.com",
    customerId: "CUST004",
    shoppingCartId: "CART004",
    subTotal: 199.99,
  },
  {
    orderStatus: "Processing",
    bcStatus: "Paid",
    order: "ORD005",
    storeName: "Book Haven",
    date: "2024-01-14",
    customerBillingInfo: {
      firstName: "Lisa",
      lastName: "Chen",
      city: "Seattle",
      state: "WA",
      pincode: "98101",
      streetAddress1: "567 Maple Dr",
      streetAddress2: "Floor 3",
    },
    total: 89.99,
    paymentType: "Credit Card",
    paymentStatus: "Completed",
    fulfillmentStatus: "In Progress",
    items: [
      {
        productName: "Fiction Novel",
        productPrice: 14.99,
        productStatus: "In Stock",
        productQuantity: 3,
        productImage: "https://example.com/novel.jpg",
        productSku: "BK001",
        productColor: "Paperback",
        productTotal: 44.97,
      },
      {
        productName: "Cookbook",
        productPrice: 24.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/cookbook.jpg",
        productSku: "BK002",
        productColor: "Hardcover",
        productTotal: 24.99,
      },
      {
        productName: "Children's Book",
        productPrice: 9.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/kids-book.jpg",
        productSku: "BK003",
        productColor: "Paperback",
        productTotal: 19.98,
      },
    ],
    shippingMethod: "Ground Shipping",
    storeLogoUrl: "https://example.com/store5-logo.png",
    name: "Book Collection",
    createdDate: "2024-01-14T13:20:00",
    createdName: "Lisa Chen",
    modifiedDate: "2024-01-14T14:30:00",
    modifiedName: "Lisa Chen",
    email: "customer5@example.com",
    customerId: "CUST005",
    shoppingCartId: "CART005",
    subTotal: 89.99,
  },
  {
    orderStatus: "Completed",
    bcStatus: "Fulfilled",
    order: "ORD006",
    storeName: "Pet Supplies",
    date: "2024-01-13",
    customerBillingInfo: {
      firstName: "David",
      lastName: "Park",
      city: "Miami",
      state: "FL",
      pincode: "33101",
      streetAddress1: "890 Cedar Ln",
      streetAddress2: "",
    },
    total: 156.5,
    paymentType: "PayPal",
    paymentStatus: "Completed",
    fulfillmentStatus: "Delivered",
    items: [
      {
        productName: "Dog Food",
        productPrice: 45.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/dog-food.jpg",
        productSku: "DF001",
        productColor: "N/A",
        productTotal: 91.98,
      },
      {
        productName: "Cat Toys Set",
        productPrice: 19.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/cat-toys.jpg",
        productSku: "CT001",
        productColor: "Multicolor",
        productTotal: 19.99,
      },
      {
        productName: "Pet Bed",
        productPrice: 44.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/pet-bed.jpg",
        productSku: "PB001",
        productColor: "Gray",
        productTotal: 44.99,
      },
    ],
    shippingMethod: "Express Shipping",
    storeLogoUrl: "https://example.com/store6-logo.png",
    name: "Pet Care Bundle",
    createdDate: "2024-01-13T10:15:00",
    createdName: "David Park",
    modifiedDate: "2024-01-13T11:45:00",
    modifiedName: "David Park",
    email: "customer6@example.com",
    customerId: "CUST006",
    shoppingCartId: "CART006",
    subTotal: 156.5,
  },
  {
    orderStatus: "Cancelled",
    bcStatus: "Cancelled",
    order: "ORD007",
    storeName: "Toy World",
    date: "2024-01-12",
    customerBillingInfo: {
      firstName: "Rachel",
      lastName: "Green",
      city: "Boston",
      state: "MA",
      pincode: "02101",
      streetAddress1: "234 Birch St",
      streetAddress2: "Apt 15",
    },
    total: 79.99,
    paymentType: "Credit Card",
    paymentStatus: "Refunded",
    fulfillmentStatus: "Cancelled",
    items: [
      {
        productName: "Building Blocks",
        productPrice: 29.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/blocks.jpg",
        productSku: "BB001",
        productColor: "Multicolor",
        productTotal: 29.99,
      },
      {
        productName: "Remote Control Car",
        productPrice: 49.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/rc-car.jpg",
        productSku: "RC001",
        productColor: "Red",
        productTotal: 49.99,
      },
    ],
    shippingMethod: "Standard Shipping",
    storeLogoUrl: "https://example.com/store7-logo.png",
    name: "Kids Toys Bundle",
    createdDate: "2024-01-12T15:30:00",
    createdName: "Rachel Green",
    modifiedDate: "2024-01-12T16:45:00",
    modifiedName: "Rachel Green",
    email: "customer7@example.com",
    customerId: "CUST007",
    shoppingCartId: "CART007",
    subTotal: 79.99,
  },
  {
    orderStatus: "Processing",
    bcStatus: "Paid",
    order: "ORD008",
    storeName: "Garden Center",
    date: "2024-01-15",
    customerBillingInfo: {
      firstName: "Tom",
      lastName: "Wilson",
      city: "Denver",
      state: "CO",
      pincode: "80201",
      streetAddress1: "456 Rose Ave",
      streetAddress2: "Unit 3B",
    },
    total: 245.75,
    paymentType: "Debit Card",
    paymentStatus: "Completed",
    fulfillmentStatus: "In Progress",
    items: [
      {
        productName: "Garden Shovel",
        productPrice: 34.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/shovel.jpg",
        productSku: "GS001",
        productColor: "Green",
        productTotal: 69.98,
      },
      {
        productName: "Plant Pots Set",
        productPrice: 49.99,
        productStatus: "In Stock",
        productQuantity: 3,
        productImage: "https://example.com/pots.jpg",
        productSku: "PP001",
        productColor: "Terracotta",
        productTotal: 149.97,
      },
      {
        productName: "Garden Gloves",
        productPrice: 12.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/gloves.jpg",
        productSku: "GG001",
        productColor: "Brown",
        productTotal: 25.98,
      },
    ],
    shippingMethod: "Ground Shipping",
    storeLogoUrl: "https://example.com/store8-logo.png",
    name: "Garden Tools Set",
    createdDate: "2024-01-15T09:20:00",
    createdName: "Tom Wilson",
    modifiedDate: "2024-01-15T10:30:00",
    modifiedName: "Tom Wilson",
    email: "customer8@example.com",
    customerId: "CUST008",
    shoppingCartId: "CART008",
    subTotal: 245.75,
  },
  {
    orderStatus: "Pending",
    bcStatus: "Awaiting Payment",
    order: "ORD009",
    storeName: "Music Store",
    date: "2024-01-14",
    customerBillingInfo: {
      firstName: "James",
      lastName: "Lee",
      city: "Portland",
      state: "OR",
      pincode: "97201",
      streetAddress1: "789 Melody Ln",
      streetAddress2: "",
    },
    total: 599.99,
    paymentType: "Credit Card",
    paymentStatus: "Pending",
    fulfillmentStatus: "Not Started",
    items: [
      {
        productName: "Electric Guitar",
        productPrice: 599.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/guitar.jpg",
        productSku: "EG001",
        productColor: "Sunburst",
        productTotal: 599.99,
      },
    ],
    shippingMethod: "Express Shipping",
    storeLogoUrl: "https://example.com/store9-logo.png",
    name: "Guitar Package",
    createdDate: "2024-01-14T14:15:00",
    createdName: "James Lee",
    modifiedDate: "2024-01-14T15:20:00",
    modifiedName: "James Lee",
    email: "customer9@example.com",
    customerId: "CUST009",
    shoppingCartId: "CART009",
    subTotal: 599.99,
  },
  {
    orderStatus: "Completed",
    bcStatus: "Fulfilled",
    order: "ORD010",
    storeName: "Art Supplies",
    date: "2024-01-13",
    customerBillingInfo: {
      firstName: "Emma",
      lastName: "White",
      city: "Austin",
      state: "TX",
      pincode: "73301",
      streetAddress1: "123 Canvas Rd",
      streetAddress2: "Studio 5",
    },
    total: 178.5,
    paymentType: "PayPal",
    paymentStatus: "Completed",
    fulfillmentStatus: "Delivered",
    items: [
      {
        productName: "Paint Set",
        productPrice: 49.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/paint.jpg",
        productSku: "PS001",
        productColor: "Assorted",
        productTotal: 99.98,
      },
      {
        productName: "Canvas Pack",
        productPrice: 29.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/canvas.jpg",
        productSku: "CP001",
        productColor: "White",
        productTotal: 59.98,
      },
      {
        productName: "Brush Set",
        productPrice: 19.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/brushes.jpg",
        productSku: "BS001",
        productColor: "Brown",
        productTotal: 19.99,
      },
    ],
    shippingMethod: "Standard Shipping",
    storeLogoUrl: "https://example.com/store10-logo.png",
    name: "Artist Kit",
    createdDate: "2024-01-13T11:30:00",
    createdName: "Emma White",
    modifiedDate: "2024-01-13T12:45:00",
    modifiedName: "Emma White",
    email: "customer10@example.com",
    customerId: "CUST010",
    shoppingCartId: "CART010",
    subTotal: 178.5,
  },
  {
    orderStatus: "Processing",
    bcStatus: "Paid",
    order: "ORD011",
    storeName: "Kitchen Essentials",
    date: "2024-01-15",
    customerBillingInfo: {
      firstName: "Sophie",
      lastName: "Martinez",
      city: "San Diego",
      state: "CA",
      pincode: "92101",
      streetAddress1: "567 Cook St",
      streetAddress2: "Apt 2C",
    },
    total: 349.99,
    paymentType: "Credit Card",
    paymentStatus: "Completed",
    fulfillmentStatus: "In Progress",
    items: [
      {
        productName: "Cookware Set",
        productPrice: 199.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/cookware.jpg",
        productSku: "CS001",
        productColor: "Stainless Steel",
        productTotal: 199.99,
      },
      {
        productName: "Knife Set",
        productPrice: 89.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/knives.jpg",
        productSku: "KS001",
        productColor: "Black",
        productTotal: 89.99,
      },
      {
        productName: "Cutting Board",
        productPrice: 29.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/board.jpg",
        productSku: "CB001",
        productColor: "Bamboo",
        productTotal: 59.98,
      },
    ],
    shippingMethod: "Ground Shipping",
    storeLogoUrl: "https://example.com/store11-logo.png",
    name: "Cooking Set",
    createdDate: "2024-01-15T10:45:00",
    createdName: "Sophie Martinez",
    modifiedDate: "2024-01-15T11:50:00",
    modifiedName: "Sophie Martinez",
    email: "customer11@example.com",
    customerId: "CUST011",
    shoppingCartId: "CART011",
    subTotal: 349.99,
  },
  {
    orderStatus: "Pending",
    bcStatus: "Awaiting Payment",
    order: "ORD012",
    storeName: "Outdoor Gear",
    date: "2024-01-14",
    customerBillingInfo: {
      firstName: "Chris",
      lastName: "Taylor",
      city: "Phoenix",
      state: "AZ",
      pincode: "85001",
      streetAddress1: "890 Trail Way",
      streetAddress2: "",
    },
    total: 799.99,
    paymentType: "Debit Card",
    paymentStatus: "Pending",
    fulfillmentStatus: "Not Started",
    items: [
      {
        productName: "Camping Tent",
        productPrice: 399.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/tent.jpg",
        productSku: "CT001",
        productColor: "Green",
        productTotal: 399.99,
      },
      {
        productName: "Sleeping Bag",
        productPrice: 199.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/sleeping-bag.jpg",
        productSku: "SB001",
        productColor: "Blue",
        productTotal: 399.98,
      },
    ],
    shippingMethod: "Express Shipping",
    storeLogoUrl: "https://example.com/store12-logo.png",
    name: "Camping Equipment",
    createdDate: "2024-01-14T13:15:00",
    createdName: "Chris Taylor",
    modifiedDate: "2024-01-14T14:25:00",
    modifiedName: "Chris Taylor",
    email: "customer12@example.com",
    customerId: "CUST012",
    shoppingCartId: "CART012",
    subTotal: 799.99,
  },
  {
    orderStatus: "Completed",
    bcStatus: "Fulfilled",
    order: "ORD013",
    storeName: "Beauty Shop",
    date: "2024-01-13",
    customerBillingInfo: {
      firstName: "Nina",
      lastName: "Rodriguez",
      city: "Atlanta",
      state: "GA",
      pincode: "30301",
      streetAddress1: "234 Glamour Ave",
      streetAddress2: "Suite 8",
    },
    total: 129.99,
    paymentType: "PayPal",
    paymentStatus: "Completed",
    fulfillmentStatus: "Shipped",
    items: [
      {
        productName: "Face Cream",
        productPrice: 39.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/face-cream.jpg",
        productSku: "FC001",
        productColor: "N/A",
        productTotal: 79.98,
      },
      {
        productName: "Serum",
        productPrice: 49.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/serum.jpg",
        productSku: "SR001",
        productColor: "N/A",
        productTotal: 49.99,
      },
    ],
    shippingMethod: "Standard Shipping",
    storeLogoUrl: "https://example.com/store13-logo.png",
    name: "Skincare Bundle",
    createdDate: "2024-01-13T09:30:00",
    createdName: "Nina Rodriguez",
    modifiedDate: "2024-01-13T10:45:00",
    modifiedName: "Nina Rodriguez",
    email: "customer13@example.com",
    customerId: "CUST013",
    shoppingCartId: "CART013",
    subTotal: 129.99,
  },
  {
    orderStatus: "Processing",
    bcStatus: "Paid",
    order: "ORD014",
    storeName: "Office Supplies",
    date: "2024-01-15",
    customerBillingInfo: {
      firstName: "Peter",
      lastName: "Chang",
      city: "Dallas",
      state: "TX",
      pincode: "75201",
      streetAddress1: "456 Business Blvd",
      streetAddress2: "Floor 4",
    },
    total: 234.5,
    paymentType: "Credit Card",
    paymentStatus: "Completed",
    fulfillmentStatus: "In Progress",
    items: [
      {
        productName: "Desk Chair",
        productPrice: 149.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/chair.jpg",
        productSku: "DC001",
        productColor: "Black",
        productTotal: 149.99,
      },
      {
        productName: "Desk Lamp",
        productPrice: 34.99,
        productStatus: "In Stock",
        productQuantity: 1,
        productImage: "https://example.com/desk-lamp.jpg",
        productSku: "DL001",
        productColor: "Silver",
        productTotal: 34.99,
      },
      {
        productName: "Stationery Set",
        productPrice: 24.99,
        productStatus: "In Stock",
        productQuantity: 2,
        productImage: "https://example.com/stationery.jpg",
        productSku: "SS001",
        productColor: "Assorted",
        productTotal: 49.98,
      },
    ],
    shippingMethod: "Ground Shipping",
    storeLogoUrl: "https://example.com/store14-logo.png",
    name: "Office Bundle",
    createdDate: "2024-01-15T11:20:00",
    createdName: "Peter Chang",
    modifiedDate: "2024-01-15T12:30:00",
    modifiedName: "Peter Chang",
    email: "customer14@example.com",
    customerId: "CUST014",
    shoppingCartId: "CART014",
    subTotal: 234.5,
  },
];
