import { IproductCalculationReportList } from "@/types/product-calculation-report/productCalculationReportList.type";
export const PRODUCT_DUMMY_LIST: IproductCalculationReportList[] = [
  {
    product_name: "*Backorder* USAA Healthy Points Beanie - White",
    sku: "US0R018AS",
    boston_beer: "CrossIcon",
    bacardi_grey_goose: "CrossIcon",
    cyxtera: "CrossIcon",
    simpliSafe: "CrossIcon",
    the_home_depot: "CrossIcon",
    unit1: "CrossIcon",
    USAA_alpha_healthy_points: "CrossIcon",
    Usaa_Claims_Apparel: "CrossIcon",
    Usaa_Healthy_Points: "CrossIcon",
    Usaa_Punchout: "CrossIcon",
    Porsche: "CrossIcon",
    Skadden_Holiday_Store: "CrossIcon",
    Stryker: "CrossIcon",
    USAA_NEO_Shirts: "CrossIcon",
  },
  {
    product_name:
      "*LIMITED STOCK* TOMMY BAHAMA MEN'S PALMETTO PARADISE POLO - SAM ADAMS",
    sku: "SA0A044LC",
    boston_beer: "SuccessCheckmark",
    bacardi_grey_goose: "CrossIcon",
    cyxtera: "CrossIcon",
    simpliSafe: "CrossIcon",
    the_home_depot: "CrossIcon",
    unit1: "CrossIcon",
    USAA_alpha_healthy_points: "CrossIcon",
    Usaa_Claims_Apparel: "CrossIcon",
    Usaa_Healthy_Points: "CrossIcon",
    Usaa_Punchout: "CrossIcon",
    Porsche: "CrossIcon",
    Skadden_Holiday_Store: "CrossIcon",
    Stryker: "CrossIcon",
    USAA_NEO_Shirts: "CrossIcon",
  },
  {
    product_name:
      "*LIMITED STOCK* TOMMY BAHAMA MEN'S PALMETTO PARADISE POLO - TRULY",
    sku: "TLOA024LC",
    boston_beer: "SuccessCheckmark",
    bacardi_grey_goose: "CrossIcon",
    cyxtera: "CrossIcon",
    simpliSafe: "CrossIcon",
    the_home_depot: "CrossIcon",
    unit1: "CrossIcon",
    USAA_alpha_healthy_points: "CrossIcon",
    Usaa_Claims_Apparel: "CrossIcon",
    Usaa_Healthy_Points: "CrossIcon",
    Usaa_Punchout: "CrossIcon",
    Porsche: "CrossIcon",
    Skadden_Holiday_Store: "CrossIcon",
    Stryker: "CrossIcon",
    USAA_NEO_Shirts: "CrossIcon",
  },
  {
    product_name:
      "*LIMITED STOCK* TOMMY BAHAMA MEN'S TROPIC ISLES SHIRT - LOMA VISTA",
    sku: "LV0C002LS",
    boston_beer: "SuccessCheckmark",
    bacardi_grey_goose: "CrossIcon",
    cyxtera: "CrossIcon",
    simpliSafe: "CrossIcon",
    the_home_depot: "CrossIcon",
    unit1: "CrossIcon",
    USAA_alpha_healthy_points: "CrossIcon",
    Usaa_Claims_Apparel: "CrossIcon",
    Usaa_Healthy_Points: "CrossIcon",
    Usaa_Punchout: "CrossIcon",
    Porsche: "CrossIcon",
    Skadden_Holiday_Store: "CrossIcon",
    Stryker: "CrossIcon",
    USAA_NEO_Shirts: "CrossIcon",
  },
  {
    product_name:
      "*LIMITED STOCK* TOMMY BAHAMA MEN'S TROPIC ISLES SHIRT - TRULY",
    sku: "TLOC012LC",
    boston_beer: "SuccessCheckmark",
    bacardi_grey_goose: "CrossIcon",
    cyxtera: "CrossIcon",
    simpliSafe: "CrossIcon",
    the_home_depot: "CrossIcon",
    unit1: "CrossIcon",
    USAA_alpha_healthy_points: "CrossIcon",
    Usaa_Claims_Apparel: "CrossIcon",
    Usaa_Healthy_Points: "CrossIcon",
    Usaa_Punchout: "CrossIcon",
    Porsche: "CrossIcon",
    Skadden_Holiday_Store: "CrossIcon",
    Stryker: "CrossIcon",
    USAA_NEO_Shirts: "CrossIcon",
  },
];
