export const PRODUCT_SAMPLE_DATA = [
  {
    id: 1,
    productImage: [
      "https://storagemedia.corporategear.com/betastoragemedia/1/mastercatalog/attributeimages/ms25ek15s-bsea_1.jpg",
      "https://storagemedia.corporategear.com/betastoragemedia/1/mastercatalog/attributeimages/ms25ek15s-bsea_1.jpg",
    ],
    productName: "Classic Cotton T-Shirt",
    brandName: "Premium Basics",
    category: "Apparel",
    vendorSKU: "VND-001",
    sku: "CTN-TSH-001",
    quantity: 150,
    customerPrice: 29.99,
    lastBCSyncDate: "2024-03-15",
    bcSyncStatus: "Active",
    status: "Active",
    variants: [
      { id: 1, color: "Black" },
      { id: 2, color: "White" },
    ],
    subRows: [
      {
        id: "1-1",
        productImage: [
          "https://storagemedia.corporategear.com/betastoragemedia/1/mastercatalog/attributeimages/ms25ek15s-bsea_1.jpg",
        ],
        productName: "Classic Cotton T-Shirt - Black",
        brandName: "Premium Basics",
        category: "Apparel",
        vendorSKU: "VND-001-BLK",
        sku: "CTN-TSH-001-BLK",
        quantity: 75,
        customerPrice: 29.99,
        lastBCSyncDate: "2024-03-15",
        bcSyncStatus: "Active",
        status: "Active",
      },
      {
        id: "1-2",
        productImage: [
          "https://storagemedia.corporategear.com/betastoragemedia/1/mastercatalog/attributeimages/ms25ek15s-bsea_1.jpg",
        ],
        productName: "Classic Cotton T-Shirt - White",
        brandName: "Premium Basics",
        category: "Apparel",
        vendorSKU: "VND-001-WHT",
        sku: "CTN-TSH-001-WHT",
        quantity: 75,
        customerPrice: 29.99,
        lastBCSyncDate: "2024-03-15",
        bcSyncStatus: "Active",
        status: "Active",
      },
    ],
  },
  {
    id: 2,
    productImage: [
      "https://storagemedia.corporategear.com/betastoragemedia/1/mastercatalog/attributeimages/ms25ek15s-bsea_1.jpg",
    ],
    productName: "Professional Laptop Backpack",
    brandName: "TechGear",
    category: "Accessories",
    vendorSKU: "VND-002",
    sku: "BPK-001",
    quantity: 75,
    customerPrice: 89.99,
    lastBCSyncDate: "2024-03-14",
    bcSyncStatus: "Active",
    status: "Active",
  },
  {
    id: 3,
    productImage: null,
    productName: "Wireless Mouse",
    brandName: "TechGear",
    category: "Electronics",
    vendorSKU: "VND-003",
    sku: "WM-001",
    quantity: 200,
    customerPrice: 34.99,
    lastBCSyncDate: "2024-03-13",
    bcSyncStatus: "Inactive",
    status: "Inactive",
  },
];

export const MASTER_SAMPLE_DATA = [
  {
    id: 1,
    productImage: "/noImage.jpg",
    productName: "Sample Product",
    brandName: "Sample Brand",
    categoryName: "Sample Category",
    vendorSKU: "V-SKU-001",
    sku: "SKU-001",
    quantity: 100,
    customerPrice: 29.99,
  },
];
