export const data = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    role: "Admin",
    lastLoginTime: "2024-03-20T10:30:00",
    createdDate: "2024-01-15T09:00:00",
    createdName: "System Admin",
    modifiedDate: "2024-03-19T14:20:00",
    modifiedName: "John Doe",
    recStatus: "A",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    role: "Manager",
    lastLoginTime: "2024-03-19T15:45:00",
    createdDate: "2024-01-20T11:30:00",
    createdName: "System Admin",
    modifiedDate: "2024-03-18T16:15:00",
    modifiedName: "Jane Smith",
    recStatus: "I",
  },
  {
    id: 3,
    name: "Mike Johnson",
    email: "mike.j@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    role: "User",
    lastLoginTime: "2024-03-18T09:20:00",
    createdDate: "2024-02-01T10:00:00",
    createdName: "John Doe",
    modifiedDate: "2024-03-17T11:30:00",
    modifiedName: "John Doe",
    recStatus: "A",
  },
  {
    id: 4,
    name: "Sarah Williams",
    email: "sarah.w@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    role: "Manager",
    lastLoginTime: "2024-03-20T08:15:00",
    createdDate: "2024-02-10T14:20:00",
    createdName: "Jane Smith",
    modifiedDate: "2024-03-19T09:45:00",
    modifiedName: "Sarah Williams",
    recStatus: "I",
  },
  {
    id: 5,
    name: "David Brown",
    email: "david.b@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    role: "User",
    lastLoginTime: "2024-03-17T16:30:00",
    createdDate: "2024-02-15T13:00:00",
    createdName: "John Doe",
    modifiedDate: "2024-03-16T15:20:00",
    modifiedName: "David Brown",
    recStatus: "P",
  },
  {
    id: 6,
    name: "Emily Davis",
    email: "emily.d@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    role: "Admin",
    lastLoginTime: "2024-03-20T11:45:00",
    createdDate: "2024-02-20T09:30:00",
    createdName: "Sarah Williams",
    modifiedDate: "2024-03-19T10:15:00",
    modifiedName: "Emily Davis",
    recStatus: "A",
  },
  {
    id: 7,
    name: "Alex Turner",
    email: "alex.t@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    role: "User",
    lastLoginTime: "2024-03-19T14:20:00",
    createdDate: "2024-02-25T11:45:00",
    createdName: "Emily Davis",
    modifiedDate: "2024-03-18T13:30:00",
    modifiedName: "Alex Turner",
    recStatus: "I",
  },
  {
    id: 8,
    name: "Lisa Anderson",
    email: "lisa.a@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
    role: "Manager",
    lastLoginTime: "2024-03-20T09:30:00",
    createdDate: "2024-03-01T10:20:00",
    createdName: "John Doe",
    modifiedDate: "2024-03-19T08:45:00",
    modifiedName: "Lisa Anderson",
    recStatus: "A",
  },
  {
    id: 9,
    name: "Robert Wilson",
    email: "robert.w@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
    role: "User",
    lastLoginTime: "2024-03-18T15:40:00",
    createdDate: "2024-03-05T14:15:00",
    createdName: "Sarah Williams",
    modifiedDate: "2024-03-17T16:20:00",
    modifiedName: "Robert Wilson",
    recStatus: "A",
  },
  {
    id: 10,
    name: "Emma Taylor",
    email: "emma.t@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    role: "Manager",
    lastLoginTime: "2024-03-20T10:15:00",
    createdDate: "2024-03-10T09:30:00",
    createdName: "Emily Davis",
    modifiedDate: "2024-03-19T11:45:00",
    modifiedName: "Emma Taylor",
    recStatus: "P",
  },
];

export const reportToOptions = [
  {
    label: "Zara Patel",
    value: "zara-patel",
  },
  {
    label: "Marcus Chen",
    value: "marcus-chen",
  },
  {
    label: "Isabella Rodriguez",
    value: "isabella-rodriguez",
  },
  {
    label: "Aiden O'Connor",
    value: "aiden-oconnor",
  },
  {
    label: "Sophia Kim",
    value: "sophia-kim",
  },
  {
    label: "Jamal Thompson",
    value: "jamal-thompson",
  },
  {
    label: "Luna Nakamura",
    value: "luna-nakamura",
  },
  {
    label: "Henrik Larsson",
    value: "henrik-larsson",
  },
  {
    label: "Amara Okafor",
    value: "amara-okafor",
  },
  {
    label: "Gabriel Santos",
    value: "gabriel-santos",
  },
];

export const roleOptions = [
  {
    label: "Administrator",
    value: "administrator",
  },
  {
    label: "Manager",
    value: "manager",
  },
  {
    label: "Team Lead",
    value: "team-lead",
  },
  {
    label: "Standard User",
    value: "standard-user",
  },
  {
    label: "Read Only",
    value: "read-only",
  },
];

export const statusValues = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
  { value: "pending", label: "Pending" },
];
