async function getBundleList() {
  const response = await import("@/mock-data/bundle.json");

  return { ...response.default, items: [...response.default.items] };
}

async function getBundleDetails(bundleId: string) {
  return {
    id: 55754,
    storeId: 5,
    brandId: 0,
    vendorId: 0,
    name: "Bundle Product 1",
    isNameDifferentfromERP: false,
    nameInERP: "",
    isERPNameDifferent: false,
    erpItemId: 0,
    vendorSKU: null,
    ourSKU: "BUNDLE001",
    producttypeId: 3,
    companionProduct: null,
    taxCode: "TAX001",
    categoryId: 3,
    category: "Women",
    description: "<p>This is Bundle Product 1</p>\n",
    shortDescription: "<p>This is Bundle Product 1</p>\n",
    length: 10.0,
    width: 8.0,
    height: 1.0,
    volume: 80.0,
    weightInLBS: 0.0,
    shipWeightinLBS: 0.0,
    isBundle: false,
    dimensionTemplateId: 9,
    newUrl: "",
    ourCost: 134.32,
    msrp: 150.0,
    imap: 0.0,
    salePrice: 130.0,
    isGiftWrap: false,
    giftWrapPrice: 0.0,
    callForPrice: false,
    isEnableMAP: false,
    quantityDiscountTemplate: 0,
    ecomSafetyQty: 0.0,
    sizeChartId: 0,
    sizeChartDescription: null,
    isEnableLogolocation: false,
    personalizedCategoryId: 0,
    isNewProduct: false,
    isAssembleProduct: false,
    isDropShipProduct: false,
    isSaleProduct: false,
    isrestrictedProduct: true,
    isFeatured: false,
    isNewArrival: false,
    isbestSellar: false,
    isPriceQuote: false,
    isGiftSet: false,
    isCommingSoon: false,
    isNoCoupan: false,
    isSepateShip: false,
    isSampleProduct: false,
    recStatus: "active",
    location: "RI",
    ipAddress: "120.72.90.155",
    macAddress: "00-00-00-00-00-00",
    rowVersion: "Lix7g+333Ag=",
    createdByName: null,
    modifiedByName: null,
    createdDate: "2024-03-19T05:26:03.3427076",
    createdBy: null,
    modifiedDate: "2024-10-29T07:44:26.4965125",
    modifiedBy: "John Doe",
    seName: "bundle-product-001",
    isSENameChanged: true,
  };
}

export { getBundleDetails, getBundleList };
